### PR TITLE
Update python_moztelemetry version

### PR DESCRIPTION
**Pull request by fbertsch**
We are now on 0.5. We need to keep these versions running up to date.

@vitillo r?

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/emr-bootstrap-spark/55)

### CODE REVIEW

**Comment by vitillo** [comment]
r+

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ansible/files/telemetry.sh, line 84 at r1](https://reviewable.io:443/reviews/mozilla/emr-bootstrap-spark/55#-Kac2ufpW6BnVih_sa6u:-Kac2ufpW6BnVih_sa6v:bhrzzbf) ([raw file](https://github.com/mozilla/emr-bootstrap-spark/blob/b5bdaf4bccc18e803fb18c13e42550a42b0480d9/ansible/files/telemetry.sh#L84)):*
> ```Shell
> PIP_REQUIREMENTS_FILE=/tmp/requirements.txt
> cat << EOF > $PIP_REQUIREMENTS_FILE
> python_moztelemetry>=0.5
> ```

Please use ">=0.5,<1.0" so that human intervention is required when the next major release hits.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/emr-bootstrap-spark/55)*

**Comment by fbertsch** [comment]
@vitillo, good to go?

**Comment by vitillo** [comment]
r+

**Pull request merged**
