### PR TITLE
Install JupyterLab and a newer Jupyter Notebook.

### PR DESCRIPTION
**Pull request by jezdez**
This is in response to the recent blog post ["JupyterLab is Ready for Users"](https://blog.jupyter.org/jupyterlab-is-ready-for-users-5a6f039b8906) which indicated that installing it would suffice (and confirmed locally by me) and then going to http://localhost:8888/lab.

This would maybe be a useful thing for everyday data analysis since it allows a more streamlined process with the persisted home directory of our EMR clusters.

### CODE REVIEW

**Comment by jezdez** [comment]
Not sure who to ask to review this, @robotblake assured me though that we can deploy that to ATMO stage first and check it out there before moving it into prod.

**Comment by teonbrooks** [comment]
I am very much interested in having this capability. i've been evaluating jupyterlab locally and it would be useful to my workflow.

**Comment by teonbrooks** [comment]
I am very much interested in having this capability. i've been evaluating jupyterlab locally and it would be useful to my workflow.

**Comment by robotblake** [comment]
This should be pretty straightforward but pulling in @rafrombrc so we can have a quick conversation about it before merging.

**Pull request merged**
