### PR TITLE
Add access to fx-public-data bucket

### PR DESCRIPTION
**Pull request by fbertsch**

### CODE REVIEW

**Comment by jasonthomas** [comment]
What is the use case for this public bucket?

**Comment by fbertsch** [comment]
This is for public datasets. For example, the usage report and hardware report. Previously they were just in `telemetry-public-analysis-2` but that shouldn't be an official source for datasets we want to provide publicly. This bucket serves that purpose.

**Comment by jasonthomas** [comment]
I have a few questions but might be out of scope for this PR. If there is a bug or documentation detailing this information that would be good as well.

- How are we going to distribute these datasets? Are users expected to traverse the s3 path and copy down parquet files or are we provide them via a packaged form e.g. tar, zip, etc.
- How are users going to discover these datasets? Are we going to publish the links/paths on dashboards?
- `telemetry-public-analysis-2` is also fronted by a cloudfront distribution, is that something we also need here? 

I don't have a problem with adding a public bucket for use with public datasets but I am not 100% sure if this bucket should live in the Dev IAM. I am thinking the Data IAM instead. Since this will public facing I think it should be ops managed resource.

**Comment by fbertsch** [comment]
@jasonthomas you make very good points. I agree that this should be an ops managed resource and that it should have a CDN cache.

These datasets aren't necessarily distributed as-is, they are used to power the reports themselves. In the future we could see there being datasets that exist solely for public use as data, in which case we can decide on packaging and formatting at that time.

**Comment by fbertsch** [comment]
Closing this in favor of the ops-sponsored bucket.

**Pull request closed without merging**
