### PR TITLE
Add both production and staging deploy buckets

### PR DESCRIPTION
**Pull request by robhudson**
ATMO side change:
https://github.com/mozilla/telemetry-analysis-service/pull/587

### CODE REVIEW

**Comment by robhudson** [comment]
Note: The cloudformation.json updates the IAM roles. Deploying to staging will break production b/c it overwrites the telemetry-spark-emr policy and doesn't include access to the production bucket. A solution will need to be found for this -- either also have a staging policy, or always include both production/stage buckets in the policy. I'm learning towards the latter.

**Comment by robhudson** [comment]
@fbertsch Do you have a preference for handling the IAM roles that are populated with the cloudformation.json?

**Comment by fbertsch** [comment]
@robhudson I'd lean towards the former, having separate policies for stage and prod. Having read-only access to prod infra on stage (or no access at all) would guarantee that things on stage will only effect stage. How difficult do you think it would be to separate those out?

@mreid-moz - any thoughts here?

**Comment by robhudson** [comment]
I don't think it is hard at all. The ansible config creates the IAM role. For the staging deploy it can just create the staging role that only has access to the staging s3 contents.

**Comment by mreid-moz** [comment]
+1 for having separate policies for Stage and Prod - it's nice to know that things in stage do not have permission to write to prod buckets.

**Comment by robhudson** [comment]
This is ready for another review before merging.

I've tested this by deploying using the ansible script and verifying changes via the AWS console. I also launched clusters and scheduled jobs locally with ATMO using the stage bucket for bootstrapping and confirmed that it's using the stage bootstrap S3 bucket and clusters/jobs worked as expected.

**Pull request merged**
