### PR TITLE
Don't pull in rvitillo's dot files (bug #1243068)

### PR DESCRIPTION
**Pull request by whd**

### CODE REVIEW

**Comment by vitillo** [comment]
Does epel have a recent emacs version? We might want to avoid install our own in that case.

**Comment by whd** [comment]
In https://github.com/mozilla/emr-bootstrap-spark/pull/11 I mentioned I was in favor of not pulling those down anymore. I can update this PR to that effect.

**Comment by vitillo** [comment]
Please do.

**Comment by whd** [comment]
Done.

**Comment by vitillo** [comment]
r+

**Pull request merged**
