### PR TITLE
Make paths relative to deploy.yml file

### PR DESCRIPTION
**Pull request by fbertsch**
See https://github.com/ansible/ansible/issues/14341

Here is my `ansible-playbook --version` output:
```
ansible-playbook 2.1.2.0
  config file =
  configured module search path = Default w/o overrides
```

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/emr-bootstrap-spark/56)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by fbertsch** [comment]
@vitillo r?

**Comment by sunahsuh** [comment]
When we dealth with this in telemetry-airflow we used `{{ playbook_dir }}`, which keeps the changes backward compatible:
https://github.com/mozilla/telemetry-airflow/pull/60/files

**Comment by vitillo** [comment]
@fbertsch: r+ after following @sunahsuh's suggestion

**Comment by fbertsch** [comment]
Perfect, thanks!

**Pull request merged**
