### PR TITLE
Added feather and arrow libraries

### PR DESCRIPTION
**Pull request by saptarshiguha**
Feather is a interoperable data format and arrow is a time library.
https://github.com/wesm/feather and http://arrow.readthedocs.io/en/latest/

### CODE REVIEW

**Comment by robhudson** [comment]
Hi. Can I get a sense of urgency with these? The current master has a lot of changes we are currently testing. Can these wait until after those changes are rolled out, maybe in about 1 week?

**Comment by saptarshiguha** [comment]
No urgency, they are nice to have. Happy to wait.

**Comment by jezdez** [comment]
Wait, this was not good, feather's package on PyPI is called `feather-format` not `feather`.

**Comment by jezdez** [comment]
I also think you meant to install `pyarrow`, since that's the dependency of `feather`? https://github.com/wesm/feather/blob/be5141bf3c4013c046ec44776b864845b8e458ad/python/setup.py#L71

**Pull request merged**
