### PR TITLE
Bug 1334646 - Use examples from mozilla-reports

### PR DESCRIPTION
**Pull request by acmiyaguchi**
The notebooks in the examples folder have all been added to [mozilla-reports](https://github.com/mozilla/mozilla-reports ). This adds the header that is required by the `knowledge_repo` tool.

r? @vitillo

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/emr-bootstrap-spark/54)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by vitillo** [comment]
What about having the bootstrap script fetch directly the notebooks from mozilla-reports? I would like to avoid duplicating notebooks in different repos.

**Comment by vitillo** [comment]
@acmiyaguchi can you please complete this work?

**Comment by acmiyaguchi** [comment]
I've deleted the notebooks from this repository and pointed the telemetry.sh script to download from the RTMO locations.

**Pull request merged**
