### PR TITLE
Bug 1309386 - Use our internal EPEL mirror

### PR DESCRIPTION
**Pull request by robotblake**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/emr-bootstrap-spark/49)

### CODE REVIEW

**Comment by vitillo** [comment]
Has this been tested?

**Comment by robotblake** [comment]
On emr-4.5.0 and emr-5.0.0.

**Comment by vitillo** [comment]
👍

**Comment by fbertsch** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/emr-bootstrap-spark/49#-:-KTu56QUk7QyZjLdOSuz:bnfp4nl)*

**Comment by fbertsch** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/emr-bootstrap-spark/49)*

**Pull request merged**
